# -*- coding: utf-8 -*-
"""s3_telegram_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZwkLdP0nXpFOKcwNJ5LtPb15N5ckjmS
"""

# from google.colab import files

# # Python 파일 업로드
# uploaded = files.upload()

# # 업로드한 파일 이름 확인
# for filename in uploaded.keys():
#     print(f'Uploaded file: {filename}')

# # 업로드한 파일을 import
# # import my_script  # 'my_script.py'라는 파일이 업로드되었다고 가정

# # my_script.py의 함수나 클래스를 사용할 수 있습니다.
# # 예를 들어, my_script.py에 'my_function'이라는 함수가 있다면:
# # my_script.my_function()

# # github올릴 땐 지금 이 셀 주석처리해야 함

import s1_get_stock_price as getStockPrice
import s2_telegram_first as telegram


stocks = getStockPrice.setPrice(getStockPrice.stocks)
print(stocks)

text_lst = []
for _key, _value in stocks.items():
    _price = _value['price']
    text_lst.append(f'{_key} 현재가: {_price}')
# print(text_lst)
_text4tele = '\n'.join(text_lst)

telegram.tele(telegram.MY_TOKEN, telegram.myChatId, _text4tele)