# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: Python application

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# permissions:
#   contents: read

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v3
#       with:
#         python-version: "3.10"
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         pytest

# -----------------------------------------

# Actions -> Python application
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://crontab.guru/
# 한국 11오게하려면  cron에 11-9=2로 표현
# 한국 22 오게하려면 22-9 = 13
# 한국 오전 8 오게하려면 8-9 = 23
# 한국 오전 8:30 오게하려면 8-9 = 30 23
# 오전 8 월-금에 오게 하려면 0 23 * * 0-4: 여기서 UTC+9 하면 1-5(월-금)이 됨


# 5분이라 걸어놓음 10분 후 쯤 15분에 알람 옴


# cron순서 - 분 시

name: Price_Bot_250524

on:
  schedule:
    - cron : 30 23 * * 0-4
  push:
    branches: [ main ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.27.1 bs4==0.0.1

    - name: telebot
      run: |
        python s3_telegram_bot.py
